/** DHIS2 programRuleActionType values (API + rule-engine). */
export enum ProgramRuleActionType {
    HIDEFIELD = 'HIDEFIELD',
    HIDESECTION = 'HIDESECTION',
    HIDEPROGRAMSTAGE = 'HIDEPROGRAMSTAGE',
    SHOWFIELD = 'SHOWFIELD',
    SHOWWARNING = 'SHOWWARNING',
    SHOWERROR = 'SHOWERROR',
    WARNINGONCOMPLETE = 'WARNINGONCOMPLETE',
    ERRORONCOMPLETE = 'ERRORONCOMPLETE',
    ASSIGN = 'ASSIGN',
    DISPLAYTEXT = 'DISPLAYTEXT',
    DISPLAYKEYVALUEPAIR = 'DISPLAYKEYVALUEPAIR',
    HIDEOPTION = 'HIDEOPTION',
    HIDEOPTIONGROUP = 'HIDEOPTIONGROUP',
    SHOWOPTION = 'SHOWOPTION',
    SHOWOPTIONGROUP = 'SHOWOPTIONGROUP',
    SETMANDATORYFIELD = 'SETMANDATORYFIELD',
    UNSETMANDATORYFIELD = 'UNSETMANDATORYFIELD',
    SENDMESSAGE = 'SENDMESSAGE',
    SCHEDULEMESSAGE = 'SCHEDULEMESSAGE',
}

/** DHIS2 data element valueType values. */
export enum Dhis2ValueType {
    TEXT = 'TEXT',
    LONG_TEXT = 'LONG_TEXT',
    INTEGER = 'INTEGER',
    INTEGER_POSITIVE = 'INTEGER_POSITIVE',
    NUMBER = 'NUMBER',
    BOOLEAN = 'BOOLEAN',
    DATE = 'DATE',
    ORGANISATION_UNIT = 'ORGANISATION_UNIT',
    FILE_RESOURCE = 'FILE_RESOURCE',
}

/** DHIS2 programRuleVariableSourceType values. */
export enum ProgramRuleVariableSourceType {
    DATAELEMENT_PREVIOUS_EVENT = 'DATAELEMENT_PREVIOUS_EVENT',
    DATAELEMENT_CURRENT_EVENT = 'DATAELEMENT_CURRENT_EVENT',
    DATAELEMENT_NEWEST_EVENT_PROGRAM = 'DATAELEMENT_NEWEST_EVENT_PROGRAM',
    DATAELEMENT_NEWEST_EVENT_PROGRAM_STAGE = 'DATAELEMENT_NEWEST_EVENT_PROGRAM_STAGE',
    CALCULATED_VALUE = 'CALCULATED_VALUE',
    TEI_ATTRIBUTE = 'TEI_ATTRIBUTE',
}
